### ISSUE TITLE
Add more details about Praveen.

### ISSUE THREAD

**Issue by srinidhi-github-praveen** [srinidhi-github-praveen/Letter#4]
Some one should take some time to add an intro + Praveen's links on this page.

**Comment by DarshGupta1910** [comment]
Sir can I take this up?

**Comment by praveenscience** [comment]
Hi, I would like to add about myself. :) Please assign this to me. 😁

**Comment by srinidhi-github-praveen** [comment]
@praveenscience Please carry on.
